# Supabase Configuration
[supabase]
url = "YOUR_SUPABASE_URL_HERE"
key = "YOUR_SUPABASE_SERVICE_KEY_HERE"

# Premium API Keys (Optional/Future)
[api]
fmp = "YOUR_FMP_KEY"
finnhub = "YOUR_FINNHUB_KEY"


DB_USERNAME = "myuser"
DB_TOKEN = "abcdef"

[some_section]
some_key = 1234
